### ISSUE TITLE
При отладке кода исполняемого на автономном сервере версии 8.3.20.1996 отладчик EDT 2022.2.3 не показывает Серверный сеанс и не позволяет осуществлять переходы по коду

### ISSUE THREAD

**Issue by ValentinChirikov** [1C-Company/1c-edt-issues#881]
### Описание ошибки

При отладке кода исполняемого на автономном сервере версии 8.3.20.1996 отладчик EDT 2022.2.3 при срабатывании брейкпоинта не показывает Серверный сеанс и не позволяет осуществлять переходы по коду

### Как воспроизвести

1. Запущен автономный сервер вер. **8.3.20.1996**
2. Запущен сервер отладки `dbgs –port=3550`
3. EDT подключен к серверу удаленной отладки **http://127.0.0.1:3550/** имя базы **exchg**

Командная строка для запуска автономного сервера:
`start /I "IB" "C:\Program Files\1cv8\8.3.20.1996\bin\ibsrv.exe" --data="C:\DevCloud\ss" --debug="http://127.0.0.1:3550" --config="conf.yml" `

Файл настройки автономного сервера
conf.yml

```
server:
  address: 127.0.0.1
  port: 8314
database:
  path: C:\DevCloud\EXchg
infobase:
  id: 37a6640b-0706-40bd-9e36-ca424fd53a21
  name: exchg
  distribute-licenses: yes
  schedule-jobs: allow
http:
  base: /exchg
  OData:
    publish: true
  http-services:
    publish-by-default: true
gates:
  ssh:
    default:
      address: any
      port: 3551
)
```

### Скриншоты

![изображение](https://user-images.githubusercontent.com/33689101/219678692-f9692bd2-68f2-4681-93aa-6ea9790d9f4d.png)

### Ожидаемое поведение

Отладчик долже успешно останавливаться на брейкпоинте и позволять переход по-коду

### Лог рабочей области

[exchg.log](https://github.com/1C-Company/1c-edt-issues/files/10767668/exchg.log)

### Версия 1С:EDT

2022.2.3

### Операционная система

Windows

### Дополнительная информация

В процессе отладки обнаружено:
После аутентификации в клиентском приложения в метод `processEvent(DBGUIExtCmdInfoBase event) `объекта класса `RuntimeEventDispatchJob `приходит объект `event com._1c.g5.v8.dt.debug.model.dbgui.commands.impl.DBGUIExtCmdInfoQuitImpl@154a0735 (cmdIDNum: 2, cmdID: targetQuit, targetIDStr: null, requestQueueID: null)` что приводит к вызову метода `void removeThread(RuntimeDebugTargetThread thread)` объекта класса `RuntimeDebugClientTarget `который удаляет поток отладчика

Если при отладке принудительно пройти этот обработчик - то система работает штатно
